### ISSUE TITLE
Released version is not tagged

### ISSUE THREAD

**Issue by QuLogic** [robbmcleod/pyfastnoisesimd#1]
The release on PyPI does not have any tags in git to indicate the commit used.

PS, PyPI uses reST, so the readme does not render quite correctly there.

**Comment by robbmcleod** [comment]
I changed the readme, I'm not really inclined to worry about PyPI correctness on release tags so much because it's just a pain to work with PyPI.

**Comment by QuLogic** [comment]
There are still no tags on GitHub for any releases.

**Comment by robbmcleod** [comment]
This has been done now.

**Comment by QuLogic** [comment]
Thanks!
