### ISSUE TITLE
start parameter from Noise().genAsGrid() seems doesn't work

### ISSUE THREAD

**Issue by Enderlook** [robbmcleod/pyfastnoisesimd#17]
Just write:
```
>>> ns = Noise()
>>> ns.genAsGrid(shape=[3,3,3], start=[0,0,0]) == ns.genAsGrid(shape=[3,3,3], start=[50,50,50])
array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])
```
They should be different.
I'm trying to generate a huge terrain from smaller chunks using the `start` parameter, but it seems doesn't work.
Am I doing something wrong? I think it may be a bug.

**Comment by robbmcleod** [comment]
Looks to me I'm ignoring the start keyword if it's running with more than one thread.

    from pyfastnoisesimd import Noise
    ns = Noise()
    ns.numWorkers = 1
    ns.genAsGrid(shape=[3,3,3], start=[0,0,0]) == ns.genAsGrid(shape=[3,3,3], start=[50,50,50])

I'll look into it, but that will work if you want to prototype for now.

**Comment by robbmcleod** [comment]
Can you build the latest version from master and see if this is behaving as expected now?

**Comment by Enderlook** [comment]
I'm sorry but I got an error.
It's the first time I install a package from a downloaded file, so maybe the mistake was mine, but I did:

Open console:

```
cd C:\Panda3D-1.10.0-x64\python
python -m pip install C:\Users\myUser\Downloads\pyfastnoisesimd-master
```

And the output was [this pastebin](https://pastebin.com/ifqACNsc).

I can't say if the error was yours or mine because I've never installed a library from a downloaded file, I'm sorry.

**PD:** About the fix with `numWorkers` it worked perfectly, thanks! I was trying to understand why it doesn't work for a few days and I was getting very anxious!

**Comment by robbmcleod** [comment]
Ah, you would need the Microsoft Visual C++ build tools installed. They are free.

https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017

In any case I will prepare a new release.

**Comment by Enderlook** [comment]
Ok, I'll install that!

**Comment by Enderlook** [comment]
Sorry. I've installed Visual Studio Build Tools 2017: Visual C++ build tools. Then I just tried to install the library, but I got [this error](https://pastebin.com/x6pfm2Ma) (I think it's the same error). Have I downloaded the wrong stuff?
By the way, Visual Studio Build Tools doesn't use the Visual Studio IDE... open it executes a "Visual Studio 2017 Developer Command Prompt v15.0", I tried executing from there the installation and its raised a [bigger error](https://pastebin.com/7kDsYthD).
I'm sorry for making so many troubles.
Maybe have I to download "Development for Deskopt with C++"? It doesn't sound as "build tool" so I'm not sure.

**Comment by robbmcleod** [comment]
@Enderlook I've been able to resolve the memory leak and now 0.4.0 is released on PyPI, so you can try that for multi-threaded acceleration.

**Comment by robbmcleod** [comment]
Closing as I'm fairly sure this is resolved.

**Comment by Enderlook** [comment]
Yes, it works. I'm sorry for not have answered before.
