### ISSUE TITLE
seed is not respected

### ISSUE THREAD

**Issue by jgostick** [robbmcleod/pyfastnoisesimd#24]
When passing ``seed`` to the ``Noise`` class, it seems to get overwritten by the subsequent operations like setting octaves.  For instance, if I do ``perlin.seed = 0`` just before generating the image *then* it works and a consistent image is returned.  On the other hand if I do ``perlin.seed = 0`` followed other operations then ``perlin.seed`` do not return 0.

**Comment by robbmcleod** [comment]
Can you provide an example please, I don't see this on my end when I tested using `example/orthographic_projection.py`.

**Comment by jgostick** [comment]
Hmmm, I am only able to reproduce half the problem.  The ``seed`` argument is not respected.

``` python
>>> perlin = fns.Noise(numWorkers=1, seed=0)
>>> print(perlin.seed == 0)
False
```

However, when I assign seed to the ``perlin`` object it does seem to persist.  Not sure why I was find it didn't before:

``` python
>>> perlin = fns.Noise(numWorkers=1)
>>> perlin.seed = 0
>>> print(perlin.seed == 0)
True
>>> perlin.noiseType = fns.NoiseType.PerlinFractal
>>> print(perlin.seed == 0)
True
```

**Comment by robbmcleod** [comment]
Ok I see, it was checking against `bool(seed)` so specifically for the seed of 0 it would not work, and only in the constructor. Closing.
