### ISSUE TITLE
genFromCoords etc. doesn't exist as attribute

### ISSUE THREAD

**Issue by jonasjohansson** [robbmcleod/pyfastnoisesimd#26]
Attempting to run some of the examples with the end goal of generating simplex noise vec3.

Running…

`import numpy as np
import pyfastnoisesimd as fns
noise = fns.Noise()
result = noise.genFromGrid(shape=[256,256,256], start=[0,0,0])
nextResult = noise.genFromGrid(shape=[256,256,256], start=[256,0,0])`

…tells me that genFromGrid doesn't exist, and similar messages with Coords, also running examples. Any clue what I'm missing?

**Comment by robbmcleod** [comment]
It's `Noise().genAsGrid()`, not `fromGrid`.

**Comment by robbmcleod** [comment]
I see where there was a comment that used `genFromGrid(...)` and fixed it. I suggest you take a look in the `example` folder, there are some much more concrete examples there.
