### ISSUE TITLE
Install Error (Linux?) - "error: package directory 'pyfastnoisesimd' does not exist"

### ISSUE THREAD

**Issue by benjaminplanche** [robbmcleod/pyfastnoisesimd#3]
Hello again,

Install (via pip - `pip install pyfastnoisesimd` ; or locally - `python setup.py install`) is failing on my Linux system, though it goes smoothly on my Windows.

**Trace when installing with pip:**
```
Collecting pyfastnoisesimd
  Downloading pyfastnoisesimd-0.1.4.tar.gz (51kB)
    100% |████████████████████████████████| 61kB 4.2MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pyfastnoisesimd.egg-info
    writing pip-egg-info/pyfastnoisesimd.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/pyfastnoisesimd.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/pyfastnoisesimd.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/pyfastnoisesimd.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    error: package directory 'pyfastnoisesimd' does not exist
```

**Quick Fix:**

Install locally, creating the package directory yourself beforehand, i.e.:

1.  Download sources
2. Go into the source folder
3. Create package folder inside (`mkdir pyfastnoisesimd`)
4. Install (`python setup.py install`)
5. Enjoy

**Comment by robbmcleod** [comment]
Ok, looks like I've fallen prey to the dreaded `PEP-8`. Linux is case dependent and Windows isn't.   I changed the directories to be all lower-case in https://github.com/robbmcleod/PyFastNoiseSIMD/commit/7cb6bf04b058393c418f277f447621d4ac94a07f which appears to fix the problem in Ubuntu installing 0.1.5 from PyPi.

**Comment by robbmcleod** [comment]
Closing.

**Comment by robbmcleod** [comment]
Ok, it didn't actually change the directory names...

**Comment by robbmcleod** [comment]
Ok, now it looks correct on Github.  Closing.
